repos:
-   repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
    - id: trailing-whitespace
    - id: requirements-txt-fixer
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
    - id: isort
      name: isort
      entry: isort
      language: system
      types: [python]
      args: [--multi-line=3,--trailing-comma,--force-grid-wrap=0,--use-parentheses,--line-width=88]
-   repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
    - id: black
      name: black
      entry: black
      language: python
      types: [python]
      args: [--skip-string-normalization]
      language_version: python3.8
